[package]
name = "usbd-hid-toolkit"
version = "0.1.0"
edition = "2021"
description = "Batteries included rust USB HID library for usb-device"
keywords = ["no-std", "hid", "usb-device"]
authors = ["DLKJ"]
repository = "https://github.com/dlkj/usbd-hid-toolkit"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
usb-device = "0.2"
embedded-time = "0.12"